### ISSUE TITLE
Invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by kangancur** [sammy007/zcash-proxy#1]
2016/11/28 16:58:47 Loading config: /root/zcash-proxy/config.json
2016/11/28 16:58:47 Upstream: Mainnet => http://127.0.0.1:8232
2016/11/28 16:58:47 Default upstream: Mainnet => http://127.0.0.1:8232
2016/11/28 16:58:47 Error while refreshing info on Mainnet: invalid character '<' looking for beginning of value
2016/11/28 16:58:47 Unable to validate coinbase address: invalid character '<' looking for beginning of value

**Comment by sammy007** [comment]
You must specify correct rpc username and password in upstream section. I admit It's a bit confusing, I must handle status codes of RPC responses.

**Comment by kangancur** [comment]
Error while refreshing info on Mainnet: Post http://127.0.0.1:8232: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2016/11/30 13:50:06 Error while refreshing block template on Mainnet: Post http://127.0.0.1:8232: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

**Comment by sammy007** [comment]
`request canceled` = problems with rpc server. Check zcashd daemon.

**Comment by kangancur** [comment]
![screenshot_2016-12-05-10-15-41-115_com android chrome-picsay](https://cloud.githubusercontent.com/assets/8694540/20872867/bf409034-bad4-11e6-8715-8de64db57fce.png)

what the fails?

**Comment by sammy007** [comment]
Number of failed rpc requests to `zcashd`, usually timeouts or daemon errors, or network glitch.
