### ISSUE TITLE
An error occured while polling proxy state. Make sure proxy is running. 

### ISSUE THREAD

**Issue by erezrb** [sammy007/zcash-proxy#10]
Hi,

i'm getting: An error occured while polling proxy state. Make sure proxy is running. 

i'm using nginx with my default server site,

and i had this:

 location ^~ /zcash {
        alias /root/zcash-proxy/www;
        index index.html;

        try_files $uri $uri/ /zcash/index.htm;
    }

please advice :-)

thank you.

**Comment by sammy007** [comment]
You need to pass `/stats` also. And you definitely don't need nginx at all.

**Comment by erezrb** [comment]
haaa, yes:



        "frontend": {
                "listen": "0.0.0.0:8082",
                "login": "admin",
                "password": "",
                "hideIP": false
        },

it's working, thank you 👍
