### ISSUE TITLE
Is it possible mine with different difficulties?

### ISSUE THREAD

**Issue by alptolga** [sammy007/zcash-proxy#11]
I use 512 diff as you advice but some rigs are really too powerful. But there is only one diff option to use if you want to mine with all the rigs together. Would you add some extra diff to use the rigs more effective?

**Comment by sammy007** [comment]
Launch another instance with different `nonceOffset`.

**Comment by alptolga** [comment]
If you launch another offset, each of them mine independent. So it divides the power.

**Comment by sammy007** [comment]
FYI, every GPU mines independently.

**Comment by sammy007** [comment]
If you are using same offset for both instances you are mining same jobs and losing power, so you need different offsets in order to distribute work.

**Comment by alptolga** [comment]
Yes, You told it before to me. Is there any difference between 1 zcash proxy with 24 K sols and 3 zcash proxy and each of them have 8 K sols.? 
If they have same effciency, it is better to use running extra proxies for each diff. But I don't have much knowledge about it.

**Comment by sammy007** [comment]
No difference if all instances configured with different `nonceOffset`.

**Comment by alptolga** [comment]
Thank you, This is explanation is really too important for me. Because, I always thought that different instances with different nonceoffsets divide my hash power so it effect my block luck.
