### ISSUE TITLE
Implement "blocknotify", please.

### ISSUE THREAD

**Issue by dlehenky** [sammy007/zcash-proxy#12]
Really don't understand why this capability wasn't included in the original release. Considering it does away with "get-work" polling, it's a large performance improvement, dramatically reducing the latency to get new work to the miners.

**Comment by sammy007** [comment]
> wasn't included in the original release

Original release?

**Comment by dlehenky** [comment]
When you first wrote and published this proxy - when you first released it. “blocknotify” is a basic option of bitcoind/zcashd, so as a solo mining proxy, you could have included that functionality from the start, that’s all. It seems most of the open source pool software implement “blocknotify”, so I’m surprised it’s not part of zcash-proxy. It’s a relatively simple feature, and it eliminates having the proxy constantly poll the node.

**Comment by sammy007** [comment]
> It seems most of the open source pool software implement “blocknotify”

Could I take a look at these "most open source software"?

**Comment by dlehenky** [comment]
Here’s the link for Z-NOMP, a Zcash port of NOMP. The README.md describes configuring your zcashd config file and Z-NOMP to use “blocknotify” towards the bottom of the page.

Z-NOMP(Node Open Mining Portal) (READY FOR TESTING) <https://forum.z.cash/t/z-nomp-node-open-mining-portal-ready-for-testing/9738/57>

**Comment by sammy007** [comment]
I see 0 benefits of using external scripts over 500ms `getblocktemplate` poll. With 2.5m block time it does not make any sense.

**Comment by dlehenky** [comment]
I had a feeling you’d say that. It does make a difference to the miner. If I can start mining a block sooner, then it improves my chances of finding a block before someone else that's polling for work every 500 ms. Executing an external command on a modern system takes microseconds; we’re not running 8080s anymore. Anyway, fine. Just another reason why I switched to Z-NOMP for solo mining ZCL; it works very well. Have a great day!
