### ISSUE TITLE
Found my first block - ZCL, but no coins?

### ISSUE THREAD

**Issue by megacrypto** [sammy007/zcash-proxy#13]
I just found my first block but i cant see the coins in my wallet?

here is the block's info from proxy website:
```
height:  80,037	
time:     3/26/2017, 1:25 PM	
hash:     0000000245ee1ec94ac542eaffd586d2790d9118402e443b5e60a33dee9593ac
```

the info in my zclassic debug log:
```
2017-03-26 11:25:42 UpdateTip: new best=0000000245ee1ec94ac542eaffd586d2790d9118402e443b5e60a33dee9593ac  height=80037  log2_work=43.708972  tx=200708  date=2017-03-26 11:21:57 progress=0.999969  cache=2.2MiB(1630tx)
2017-03-26 11:25:42 AddToWallet d9494e45bf41322cd83b7e85741a38438ed12e2cef6f71af7826359a846e84f8  new
```

at the time i wrote this the network was at block 80066. 

thank you for your support :)

**Comment by megacrypto** [comment]
so it seems that it takes a while for balances to show up in the wallet (sorry ... this is my first block in ZEC/ZCL)

now its showing in z_gettotalbalance:

```
{
    "transparent" : "12.25",
    "private" : "0.00",
    "total" : "12.25"
}
```

but i can not see it in neither the t or z addr?

```
zcash-cli z_getbalance "zce3213Q1MVtixqWVugZ2SGL6cns2bj8GaU1vx9KmqAxMsW9JzbbqYBAW17KBadYS9d1bBhGANiSHtDjrcS9sPHGsae7kQp"
0.00000000
```

and 

```
zcash-cli listreceivedbyaddress 0 true
   {
        "address" : "t1d8Y2jmRJ859DWYaJAVouAhwjdTuuhH4D4",
        "account" : "",
        "amount" : 0.00000000,
        "confirmations" : 0,
        "txids" : [
        ]
    },
```

again, apologies for the primitive questions, but i would rather not lose my first block due to wrong procedures (from my side) 

thank you for your support

**Comment by sammy007** [comment]
Use `listtransactions` next time.
