### ISSUE TITLE
How do I purchase the source code for this project?

### ISSUE THREAD

**Issue by zeropool** [sammy007/zcash-proxy#16]
How do I purchase the source code for this project? Please contact me via github

**Comment by sammy007** [comment]
Info https://forum.z.cash/t/zcash-proxy-personal-zcash-zclassic-solo-mining-stratum/3522
Also ZenCash shit added recently.
I am available in zcash community rocket chat.

**Comment by sammy007** [comment]
You can pm me here https://chat.zcashcommunity.com I have no idea how to chat privately via github.
