### ISSUE TITLE
Error connecting dwarfpool

### ISSUE THREAD

**Issue by whitelok** [sammy007/zcash-proxy#18]
nvatp@rt5NQ2qQ:~/zcash-proxy/zcash-proxy$ ./zcash-proxy.linux config.json
2017/08/01 18:12:03 Version: devfee-408cc6c
2017/08/01 18:12:03 Loading config: /home/nvatp/zcash-proxy/zcash-proxy/config.json
2017/08/01 18:12:03 Upstream: Testnet => http://zec-us1.dwarfpool.com:3336
2017/08/01 18:12:03 Default upstream: Testnet => http://zec-us1.dwarfpool.com:3336
2017/08/01 18:12:04 Error while refreshing info on Testnet: Post http://zec-us1.dwarfpool.com:3336: EOF
2017/08/01 18:12:04 Unable to validate coinbase address: Post http://zec-us1.dwarfpool.com:3336: EOF

config file:
-------------------------
{
        "proxy": {
                "listen": "0.0.0.0:9999",
                "tls": false,
                "clientTimeout": "20m",
                "blockRefreshInterval": "1s",
                "estimationWindow": "15m",
                "luckWindow": "24h",
                "largeLuckWindow": "72h",
                "nonceOffset": 0,
                "difficulty": 8
        },

        "coinbase": "t1K9CtKh4rZXEVfjhNovozLeLysyx9AwYrH",

        "frontend": {
                "listen": "0.0.0.0:8082",
                "login": "admin",
                "password": "",
                "hideIP": false
        },

        "upstreamCheckInterval": "5s",
        "upstream": [
                {
                        "name": "Testnet",
                        "url": "http://zec-us1.dwarfpool.com:3336",
"login": "1",
                        "password": "pass",
                        "timeout": "5s"
                }
        ],

        "newrelicEnabled": false,
        "newrelicName": "MyZCashProxy",
        "newrelicKey": "SECRET_KEY",
        "newrelicVerbose": false
}

**Comment by sammy007** [comment]
What word in "solo mining" you don't understand?
