### ISSUE TITLE
When Block...

### ISSUE THREAD

**Issue by glasswool** [sammy007/zcash-proxy#19]
Hi mining for 24hrs now, @ 2200sol, shares are showing up, but no blocks yet. When will blocks show up? Am I doing something wrong?

Also what is:
 // t-address for block rewards. NOT EXCHANGE!
  "coinbase": "t1K9CtKh4rZXEVfjhNovozLeLysyx9AwYrH",

Must leave this same address or change to my taddress?

**Comment by sammy007** [comment]
My advice is to not use it and join pool. Cheers.

**Comment by sammy007** [comment]
Also, this is my address specified in config. Of course you must change it. But since you have no idea what you are doing you must mine on public pool.
