### ISSUE TITLE
Vardiff

### ISSUE THREAD

**Issue by ceozero** [sammy007/zcash-proxy#2]
Now the difficulty is not suitable for all drilling rigs, you can make an automatic adjustment of each rig used by the difficulty?

**Comment by sammy007** [comment]
Diff is static for now because it's best option for pro farms, you need blocks, not shares.

**Comment by sammy007** [comment]
If you need another difficulty, launch another proxy instance, make sure to increase `nonceOffset`, it must be different on all instances of proxy.

**Comment by ceozero** [comment]
@sammy007 But the block has come out, I'm still computing, and not submitted.
600s drilling rig, difficulty how much better.

**Comment by sammy007** [comment]
512 diff is ok for 5xGPU rig.

**Comment by ceozero** [comment]
512 diff is so big. 


I hope to be able to adjust automatically the diff.  I have too many rigs, unable to configure too many examples.

**Comment by sammy007** [comment]
`827,546` network diff is also big but you need to solve it to find a block. Diff is static for now. Period.

**Comment by ceozero** [comment]
Difficulty how to calculate the optimal value.

**Comment by ceozero** [comment]
@sammy007  the? instances of proxy.
"proxy": [
	{
		"listen": "0.0.0.0:9999",
		"clientTimeout": "20m",
		"blockRefreshInterval": "1s",
		"estimationWindow": "15m",
		"luckWindow": "24h",
		"largeLuckWindow": "72h",
		"nonceOffset": 0,
		"difficulty": 32
	},
	{
		"listen": "0.0.0.0:9988",
		"clientTimeout": "20m",
		"blockRefreshInterval": "1s",
		"estimationWindow": "15m",
		"luckWindow": "24h",
		"largeLuckWindow": "72h",
		"nonceOffset": 1,
		"difficulty": 512
	},
	{
		"listen": "0.0.0.0:9977",
		"clientTimeout": "20m",
		"blockRefreshInterval": "1s",
		"estimationWindow": "15m",
		"luckWindow": "24h",
		"largeLuckWindow": "72h",
		"nonceOffset": 2,
		"difficulty": 256
	}],

**Comment by sammy007** [comment]
Yes, different nonce offset. I invite you to simply set timeout to `1h`, find comfortable difficulty and mine with 1-2 instances. I said, no one need shares on solo, on solo you need blocks.

**Comment by ceozero** [comment]
i can't run this  proxy.

**Comment by ceozero** [comment]
@sammy007 
Can you give me a complete example in 3 difficulty degrees?
give me the config.json.  thank u.

**Comment by sammy007** [comment]
Make 3 different config files.

**Comment by ceozero** [comment]
I thought it was running on one zcash-proxy.
I see。

**Comment by axelxod** [comment]
how time for 1 block on 5 gpu and 512 diff?

**Comment by trustfarm-dev** [comment]
diff is not influence finding blocks. 
Just   check miner's hashrates accurately.
basically, Diff   higher is better, It means remove frequent hash submit overhead.

**Comment by sammy007** [comment]
Amen.
