### ISSUE TITLE
BTC-GPU Bitcoin-Gold aka Fen-Coin Please Support you child sammy otherwise make it open source

### ISSUE THREAD

**Issue by bilbobits** [sammy007/zcash-proxy#20]
https://github.com/sammy007/zcash-proxy 

equihash proxy for btg-bitcoin-gold aka fen-coin  ( fen means shit in  mandarin chinese, pronounced 'fun', like its fun to scam white idiots )  CLI, note everything is correct ./zcash-proxy.linux config.json2017/11/05 08:04:14 Version: devfee-408cc6c 2017/11/05 08:04:14 Loading config: /home/Mining/btcgpu/zcash-proxy/config.json 2017/11/05 08:04:14 Upstream: btgproxy => http://127.0.0.1:9332 2017/11/05 08:04:14 Default upstream: btgproxy => http://127.0.0.1:9332 2017/11/05 08:04:14 Error while refreshing info on btgproxy: 401 Unauthorized 2017/11/05 08:04:15 Unable to validate coinbase address: 401 Unauthorized  debug diag from bgoldd ( btcgpu daemon ), 

note that daemon is saying incorrect credentials sent, 

2017-11-05 01:04:14 Received a POST request for / from 127.0.0.1:33990 2017-11-05 01:04:14 ThreadRPCServer incorrect password attempt from 127.0.0.1:33  

Sammy U got this bitch dialed in for dev-fee 2.0, U ain't updated it  since Jan 2017, it would probably take you 5 minutes to support the fact  that BTCGPU doesn't have 'getblocksubsidy', and you could fix this  verification problem. I see you a lot here bitching to dev's about them not 'fixing' their  software, now the ball is in your court, and of course you will get  paid, you will get 2% of nada :)  

The handshaking here is that most likely zcash-proxy isn't getting a  response for 'getblocksubsidy', thus the entire proxy fails, bgoldd  daemon doesn't complete the hand-shaking and calls it off as a login  verification failure. Sammy can easily just add glue that say's that  when 'getblocksubsidy' fails cuz the CLI doesn't support it, then just  faux an ALL-ZERO data structure and be happy, as of now btcgpu  (fen-coin) doesn't support subsidy, some cold day in hell maybe the  developers will add 'getblocksubsidy' to btc-gpu and return an all-zero  json-block for subsidy ( I'm sure the dev's would love subsidy, maybe in BTC rather than fen-coin?? ) , until then sammy must step up and patch the dike.
--

**Comment by sammy007** [comment]
My [zcash-pool](https://forum.z.cash/t/zcash-proxy-personal-zcash-zclassic-solo-mining-stratum/3522) fork for BTCGPU is almost ready, then I will back port it to zcash-proxy. It's not a 5 minutes job because it requires some modifications and always requires a lot of testing.

I am still not sure if I will continue this dev-fee enabled version, not that much miners used it. Existing buyers of unlocked version of zcash-pool (zec/zcl/zen) will automatically get access to BTCGPU branch. If you are interested you can pm me in [zcash community chat](https://chat.zcashcommunity.com/).

**Comment by sammy007** [comment]
I never used `getblocksubsidy`, the BTCGPU stratum is slightly different also. Don't try to mine it with this version.

**Comment by sammy007** [comment]
BTCGPU mod available https://github.com/sammy007/zcash-proxy/releases/tag/v2.0.0
