### ISSUE TITLE
claymore

### ISSUE THREAD

**Issue by axelxod** [sammy007/zcash-proxy#3]
2016/12/01 04:34:10 Stratum miner authorization request UHD:0 192.168.1.133
2016/12/01 04:34:10 Unknown RPC method: mining.extranonce.subscribe
2016/12/01 04:34:18 Valid share at height 19651 2.0894/760642.3972 from UHD@192.168.1.133

**Comment by sammy007** [comment]
Just ignore `Unknown RPC method: mining.extranonce.subscribe`. It does not makes sense.
