### ISSUE TITLE
there isn't execute file here, just read me

### ISSUE THREAD

**Issue by erezrb** [sammy007/zcash-proxy#5]
Hi,

there isn't execute file here, just read me.

thank you for your great projects :-)

**Comment by sammy007** [comment]
It's in releases https://github.com/sammy007/zcash-proxy/releases

**Comment by erezrb** [comment]
thank you,
i can see it now only on: zcash-proxy-devfee.tar.bz2

**Comment by sammy007** [comment]
There is only one binary release with devfee so yes.
