### ISSUE TITLE
Unknown RPC method: mining.extranonce.subscribe

### ISSUE THREAD

**Issue by jorzhikgit** [sammy007/zcash-proxy#6]
Hello what that is mean?
2016/12/25 06:35:05 Stratum miner authorization request t1PBDL7i3cw9KBJwRGMwJCPY7U6yTZvA4Xh:x 2.134.27.117
2016/12/25 06:35:05 Unknown RPC method: mining.extranonce.subscribe
![zcashproxy](https://cloud.githubusercontent.com/assets/1140176/21470966/372fa0b8-cac9-11e6-950e-80ed207f0350.png)
 
Why 127.0.0.1 not accept shares?
I try with 300 ksol 24 hour

**Comment by jorzhikgit** [comment]
Or that is normal?

**Comment by sammy007** [comment]
Share is accepted, in upstream section it's a block counter, you didn't find any yet. Ignore `unknown RPC method`, it's normal. This is nonsense method added to all miners, not needed on this proxy.

**Comment by jorzhikgit** [comment]
accept on 127.0.0.1 mean that i found block?

**Comment by sammy007** [comment]
I see you are mining with 2K sol/s without any workers settings. For better experience I invite you to specify name of workers so you can see separate stats per rig. Like `Address.WorkerID` as username in miner settings.

**Comment by sammy007** [comment]
If block is found you will see "Blocks Accepted" increased in workers table. Also you will see "Accepted" in upstreams table and in the header of UI. Also you will see it in block explorer if it's not an orphan.

**Comment by jorzhikgit** [comment]
can i use this proxy for stratum to stratum?
buy nicehash and mine on other pool throght my proxy

**Comment by sammy007** [comment]
Proxy can only connect to `zcashd`. I never tested it with NH also.

**Comment by jorzhikgit** [comment]
how do think if i will mine with 200 ksol
how many time ifound block

**Comment by sammy007** [comment]
I bet you can rent any rigs and mine to proxy (this is just private pool actually). But I don't think that buying hashrate is profitable business. At current state it's zero-sum game if you are lucky.

**Comment by sammy007** [comment]
@jorzhikgit use calculators on coinwarz.com for equihash algo. Ideally a couple of blocks per day on zcash.

**Comment by jorzhikgit** [comment]
like casino :-)

**Comment by sammy007** [comment]
Solo mining is stochastic process, not best option for mining with hashrate renting services.

**Comment by jorzhikgit** [comment]
if i found 1 block day i win 100%

**Comment by sammy007** [comment]
I had a bad luck with 100K sol/s, no blocks for 3 days or so, then several blocks in a single day, so it's only for your own hashrate.

**Comment by sammy007** [comment]
Stable long term mining with well maintained farm is a key to success with solo. You will get what you deserve, average 100% luck long term, "long term" highly depends on a hashrate. 200K sol/s is ok, but maybe during a couple of weeks for smooth luck.

**Comment by alptolga** [comment]
@sammy007 is it possible to make more then one port for different difficulties? Because I have many rigs with different hashrates.

**Comment by jorzhikgit** [comment]
have i add this in my zcash.conf
gen=1
and
equihashsolver=tromp

**Comment by sammy007** [comment]
Not yet, diff is global and static per proxy instance, but you can launch several proxies with different settings, just make sure to specify different `nonceOffset`, 0, 1, 2, 3 and so forth per instance. `nonceOffset` is very necessary, otherwise your N farms will mine like a single farm.

**Comment by sammy007** [comment]
Why the hell you wanna add `gen=1`? Of course no.

**Comment by jorzhikgit** [comment]
i don't add
i ask may i need:)

**Comment by jorzhikgit** [comment]
how about equihashsolver=tromp

**Comment by sammy007** [comment]
Not needed.

**Comment by sammy007** [comment]
gen=1 is only if you wanna mine with a single core with daemon itself without external miners. it's just stupid.

**Comment by jorzhikgit** [comment]
Thanks for you

**Comment by jorzhikgit** [comment]
how about diff?

**Comment by alptolga** [comment]
@sammy007 running different proxies make different pages tomonitor rigs. But if it is the onliest way I must try.

**Comment by sammy007** [comment]
@alptolga u must connect miner to proxy with `-u something.workerID`. Like to anonymous pool.

**Comment by sammy007** [comment]
Set diff to at least to 512 and go with it, not a big deal, no one need shares only  proxy, only blocks. Set timeout to 30 minutes and go. If you are mining with CPU, reconsider mining with CPU.

**Comment by jorzhikgit** [comment]
what vps configuration must be

**Comment by sammy007** [comment]
Run on your own hardware, zcashd requires shitton of ram, will cost you 80 bucks per month.

**Comment by sammy007** [comment]
4 core, 8 GB of ram. Maybe less RAM, dunno, i have shitton so don't care.

**Comment by jorzhikgit** [comment]
in ideal i can found block with 100 sol 
like lotto
