### ISSUE TITLE
Mined block difference between zcash proxy with zclassic explorer

### ISSUE THREAD

**Issue by alptolga** [sammy007/zcash-proxy#8]
Hi,
I mined near 250 blocks with zcash proxy. It is really great. Thank you. Yestarday I restart the zcash proxy. When I checked it, it shows 30 accepted blocks but my t address shows 29 mined blocks. .What is the wrong thing?

**Comment by alptolga** [comment]
I found some details. 
This is the detail of in my log
Valid share at height 32114 25717.7245/11409.7787 from 1070_2@31.145.42.172
2017/01/01 03:53:03 Block found at height 32114 by 1070_2@31.145.42.172 [0000001462e16119588df2d911b215e5aa124628a82247cdaa0a2787a7020415]
2017/01/01 03:53:04 BLOCK SUBMIT: 
Thiere are 2 32144 blocks in block explorer. This is the same hash in my log and there is no miner address.
https://classic.zcha.in/blocks/0000001462e16119588df2d911b215e5aa124628a82247cdaa0a2787a7020415
This is the other 32114 and t address who got the block reward
https://classic.zcha.in/blocks/0000002a834301ad0a8b23e3fe5ea62ff69a18cb061f6b2bd85feff72fc69c46

**Comment by sammy007** [comment]
I see your block `0000001462e16119588df2d911b215e5aa124628a82247cdaa0a2787a7020415 ` in explorer. If it does not exist in blockchain, prolly something is wrong with explorer. Or some other block orphaned so that you have 29 blocks.

If block does not appear in blockchain it's orphaned block.

**Comment by alptolga** [comment]
That is true. There was a problem in zclassic network. My rigs mined 7 blocks in different fork due to network problem.
