### ISSUE TITLE
devfee.fee

### ISSUE THREAD

**Issue by ceozero** [sammy007/zcash-proxy#9]
I have to pay 2560.52265386 devfee. Fee, you can give me a free pool program?
![image](https://cloud.githubusercontent.com/assets/22513657/21965097/858a4602-db93-11e6-9302-066b5c6763ce.png)

**Comment by sammy007** [comment]
Yes, hedge it to BTC and PM me on slack or zcash chat.

**Comment by coolsd** [comment]
zcash pool is ok?

**Comment by sammy007** [comment]
Reach me on zclassic slack, this is issue tracker, not a marketplace.
